# Generated by Django 5.0.7 on 2024-07-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
