volumes:
  pg_data:

services:
  db:
    image: postgres:16
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  django:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - 8001:8001
