# Generated by Django 5.0.7 on 2024-08-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasklabel",
            options={"verbose_name": "метка", "verbose_name_plural": "Labels"},
        ),
        migrations.AlterField(
            model_name="tasklabel",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Name"
            ),
        ),
    ]
