# Generated by Django 5.0.7 on 2024-08-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "задача", "verbose_name_plural": "Tasks"},
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Name"
            ),
        ),
    ]
