name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: make build
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Make migrations
        run: make migrate
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Run linter
        run: flake8
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Run tests & coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        with:
          coverageCommand: make test

  build_and_push:
    name: Push to DockerHub
    runs-on: ubuntu-latest

    needs:
      - tests

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: dvsnegirev/task-manager-django:latest

  deploy:
    name: Deployment
    runs-on: ubuntu-latest

    needs:
      - build_and_push

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Copy docker-compose
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "docker-compose.production.yml"
          target: "~/task_manager_django/"

      - name: Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~task_manager_django/
            echo "${{ secrets.SSH_PASSPHRASE }}" | sudo -S docker compose -f docker-compose.production.yml down --volumes --rmi all
            echo "${{ secrets.SSH_PASSPHRASE }}" | sudo -S docker compose -f docker-compose.production.yml build --no-cache
            echo "${{ secrets.SSH_PASSPHRASE }}" | sudo -S docker compose -f docker-compose.production.yml up --force-recreate -d
            sudo docker compose -f docker-compose.production.yml exec task-manager-django make migrate
